spring:
  application:
    name: playground
  datasource:
    url: jdbc:postgresql://localhost:5437/playground
    driver-class-name: org.postgresql.Driver
    username: playground_dev
    password: playground_dev12
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    locations: classpath:db/migration
    clean-disabled: false
